tasks:
  - init: |
      docker run -d -p 3838:3838 -e ROOT=TRUE -v $(pwd):/omicsplayground/data bigomics/omicsplayground:v2.8.12


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3838
    onOpen: open-browser
