tasks:
  - init: |
      docker run -d -p 8787:8787 -e ROOT=TRUE -e PASSWORD=test12 -v $(pwd):/data bioconductor/bioconductor_docker:latest


# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8787
    onOpen: open-browser
